GeradorQRCode/Models/ErrorViewModel.cs
namespace GeradorQRCode.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GeradorQRCode/Models/QRCode.cs
using System.ComponentModel.DataAnnotations;

namespace GeradorQRCode.Models
{
    public class QRCode
    {
        [Display(Name = "Insira o texto para o QR Code")]
        [Required(ErrorMessage = "Insira um valor")]
        [StringLength(100, ErrorMessage = "Máximo de 100 caracteres para este campo")]
        public string? QRCodeText { get; set; }

        public QRCode() {}

        public QRCode(string valor)
        {
            QRCodeText = valor;
        }
    }
}

GeradorQRCode/Controllers/QRCodeController.cs
using GeradorQRCode.Models;
using IronBarCode;
using Microsoft.AspNetCore.Mvc;
using System.Drawing;

namespace GeradorQRCode.Controllers
{
    public class QRCodeController : Controller
    {
        private readonly IWebHostEnvironment _environment;

        public QRCodeController(IWebHostEnvironment environment)
        {
            _environment = environment;
        }

        public IActionResult Index()
        {
            return View("qrcode");
        }

        public IActionResult CreateQRCode(QRCode qrcode)
        {
            try
            {
                GeneratedBarcode barcode = QRCodeWriter.CreateQrCode(qrcode.QRCodeText, 200);
                barcode.AddBarcodeValueTextBelowBarcode();

                // Estilização do QRCode
                barcode.SetMargins(10);
                barcode.ChangeBarCodeColor(Color.DarkSlateGray);

                string path = Path.Combine(_environment.WebRootPath, "QRCodeGerado");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                string filePath = Path.Combine(_environment.WebRootPath, "QRCodeGerado/qrcode.png");
                barcode.SaveAsPng(filePath);
                string fileName = Path.GetFileName(filePath);
                string imageUrl = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}" + "/QRCodeGerado/" + fileName;
                ViewBag.URIQRCode = imageUrl;
            }
            catch (Exception)
            {

                throw;
            }

            return View("qrcode");
        }
    }
}

GeradorQRCode/Views/QRCode/qrcode.cshtml
@model GeradorQRCode.Models.QRCode

<h2>Gerar QRCode</h2>
<form asp-action="CreateQRCode">
    <div class="content">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group-large">
            <label asp-for="QRCodeText" class="control-label"></label>
            <input asp-for="QRCodeText" class="form-control field" />
            <span asp-validation-for="QRCodeText" class="text-danger"></span>
            <div class="form-group">
                <input type="submit" value="Gerador QR Code" class="btn btn-primary" />
            </div>
        </div>
        <div class="form-group">
            <img src="@ViewBag.URIQRCode" class="img-thumbnail" />
        </div>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

GeradorQRCode/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]GeradorQRCode</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GeradorQRCode.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="QRCode" asp-action="Index">GeradorQRCode</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GeradorQRCode
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>